services:
  dump1090:
    build:
      context: ./dump1090-docker
      dockerfile: dump1090-dockerfile
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/shm:/dev/shm
    restart: unless-stopped
    networks:
      radar-network:
  spoofradar:
    build:
      context: ./spoofradar-docker
      dockerfile: spoofradar-dockerfile
    restart: unless-stopped
    networks:
      radar-network:
    ports:
    - 80:80
    environment:
    - DUMP1090_ENDPOINT=http://dump1090:8080/data/aircraft.json
    - TEST_MODE=false
    - TEST_FILE="./samples/testing/sample_custom.json"
networks:
  radar-network:
