services:
  dump1090:
    build:
      context: ./dump1090-docker
      dockerfile: dump1090-dockerfile
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/shm:/dev/shm
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      radar-network:
  spoofradar:
    build:
      context: ./spoofradar-docker
      dockerfile: spoofradar-dockerfile
    restart: unless-stopped
    networks:
      radar-network:
    ports:
    - 80:80
    environment:
    - DUMP1090_ENDPOINT=http://10.66.2.110:8080/data/aircraft.json
    - TEST_MODE=true

networks:
  radar-network:
